ASP.NET-FinalExam-Starter-master/ASP.NET-FinalExam-Starter-master/DotNetDrinks/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetDrinks.Models
{
    public class Cart
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
        public int ProductId { get; set; }
        // how can I identify an anonymous user? Random GUID
        // where to store that GUID so that we can identify browsers? Session 
        public string CustomerId { get; set; } 
        public decimal Price { get; set; }
        public DateTime DateCreated { get; set; }

        // parent nav property
        public Product Product { get; set; }
    }
}

ASP.NET-FinalExam-Starter-master/ASP.NET-FinalExam-Starter-master/DotNetDrinks/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DotNetDrinks.Data;
using DotNetDrinks.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using DotNetDrinks.Extensions;
using Microsoft.Extensions.Configuration;
// Import necessary packages
using Stripe;
using Stripe.Checkout;

namespace DotNetDrinks.Controllers
{
    public class StoreController : Controller
    {
        private readonly ApplicationDbContext _context;
        // Use dependency injection to pass a configuration object
        private IConfiguration _configuration;

        public StoreController(ApplicationDbContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        // GET: /Store
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.OrderBy(c => c.Name).ToListAsync());
        }

        // GET: /Store/Browse/<id>
        public IActionResult Browse(int id)
        {
            // Use context object to query the database and get a list of products by categoryId
            // Use LINQ
            // https://www.tutorialsteacher.com/linq/what-is-linq
            // https://linqsamples.com/linq-to-objects/aggregation
            // https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/
            // vs SQL >> string query = "SELECT * FROM PRODUCTS WHERE CATEGORYID = @CATID";
            var products = _context.Products
                           .Where(p => p.CategoryId == id)
                           .OrderBy(p => p.Name)
                           .ToList();

            // how else can I send data back to the view?
            // ViewBag.category = _context.Categories.Where(c => c.Id == id).FirstOrDefault().Name;
            ViewBag.category = _context.Categories.Find(id).Name;

            // pass the list to be used as a model to the view
            return View(products);
        }

        // Add input names as parameters for ASP.NET to bind them automatically
        // Model binder
        // Parameter values are coming from input fields names must match
        public IActionResult AddToCart(int ProductId, int Quantity)
        {
            // query db to get product price, use LINQ
            var price = _context.Products.Find(ProductId).Price;

            // get or generate a customerid
            string customerId = GetCustomerId();

            // create and save cart object
            var cart = new Cart()
            {
                ProductId = ProductId,
                Quantity = Quantity,
                Price = price * Quantity,
                DateCreated = DateTime.UtcNow, // returns date time in UTC timezone
                CustomerId = customerId
            };

            _context.Carts.Add(cart);
            _context.SaveChanges();

            // redirect to Cart view          
            return Redirect("Cart");
        }

        public IActionResult Cart()
        {
            string customerId = GetCustomerId();
            // Use LINQ to query the Carts collection
            // Cart is a list of Products
            var cart = _context.Carts
                        .Include(c => c.Product)
                        .Where(c => c.CustomerId == customerId)
                        .ToList();

            // CALCULATE TOTAL AND PASS AS A VIEWBAG FIELD
            var total = cart.Sum(c => c.Price);
            ViewBag.TotalAmount = total.ToString("C");

            return View(cart);
        }

        public IActionResult RemoveFromCart(int id)
        {
            var cartItem = _context.Carts.Where(c => c.Id == id).FirstOrDefault();

            if (cartItem != null)
            {
                _context.Carts.Remove(cartItem);
                _context.SaveChanges();
            }

            return RedirectToAction("Cart");
        }

        [Authorize]
        public IActionResult Checkout()
        {

            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken] // Only a valid view is able to post back to the server
        public IActionResult Checkout([Bind("FirstName,LastName,Address,City,Province,PostalCode")] Models.Order order)
        {
            // populate the 3 automatic order properties
            order.OrderDate = DateTime.UtcNow;
            order.CustomerId = User.Identity.Name;

            // calculate total amount
            var cartCustomerId = GetCustomerId();
            var cartItems = _context.Carts.Where(c => c.CustomerId == cartCustomerId).ToList();
            order.Total = cartItems.Sum(c => c.Price);

            // Store order object in session and
            // Implement a nuget package
            HttpContext.Session.SetObject("Order", order);

            // Redirect to payment
            return RedirectToAction("Payment");
        }

        [Authorize]
        public IActionResult Payment()
        {
            // Get order object
            var order = HttpContext.Session.GetObject<Models.Order>("Order");
            // calculate total in cents
            ViewBag.Total = order.Total * 100;
            // read key from appsettings
            ViewBag.PublishableKey = _configuration["Stripe:PublishableKey"];

            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Payment(string stripeToken)
        {
            // get order object from session variable
            var order = HttpContext.Session.GetObject<Models.Order>("Order");

            // Import Stripe and Stripe.Checkout in your program
            // Fix any reference to Order class, declare it explicitly: Models.Order
            // get the stripe configuration key
            StripeConfiguration.ApiKey = _configuration["Stripe:SecretKey"];

            // Create Stripe session object >> https://stripe.com/docs/checkout/integration-builder
            var options = new SessionCreateOptions
            {
                PaymentMethodTypes = new List<string> { "card" },
                LineItems = new List<SessionLineItemOptions>
                {
                    new SessionLineItemOptions
                    {
                        PriceData = new SessionLineItemPriceDataOptions
                        {
                            UnitAmount = (long?)(order.Total * 100), // amount in cents
                            Currency = "cad",
                            ProductData = new SessionLineItemPriceDataProductDataOptions
                            {
                                Name = "DotNetDrinks Purchase"
                            }
                        },
                        Quantity =1
                    }
                },
                Mode = "payment",
                SuccessUrl = $"https://{Request.Host}/Store/SaveOrder",
                CancelUrl = $"https://{Request.Host}/Store/Cart"
            };

            // redirect to checkout
            var service = new SessionService(); // A service is... a class that produces something

            // now use the service object to create a session object based on the options
            // what this does is calls Stripe's API to create a session on their end
            // we have the ID value which will be used to redirect the user to Stripe
            // With this ID stripe will load the amount information on their end
            Session session = service.Create(options);

            // return json response
            return Json(new { id = session.Id });
        }

        // TODO: Create GET /Store/SaveOrder
        public IActionResult SaveOrder()
        {
            // PAYMENT IS SUCCESSFUL AND ORDER SHOULD BE CREATED IN THE DB
            // get order object from the session store
            var order = HttpContext.Session.GetObject<Models.Order>("Order");
            // save to the db
            _context.Orders.Add(order);
            _context.SaveChanges();
            // Get customerId from session store
            var customerId = GetCustomerId();
            // get all cart items to save them in the order details table > 1 cart item = 1 order details record
            var cartItems = _context.Carts.Where(c => c.CustomerId == customerId);
            // loop through the list
            foreach (var item in cartItems)
            {
                var orderDetail = new OrderDetail
                {
                    OrderId = order.Id,
                    ProductId = item.ProductId,
                    Quantity = item.Quantity,
                    Price = item.Price
                };
                _context.OrderDetails.Add(orderDetail);
            }
            _context.SaveChanges();
            // clear up cart
            foreach (var item in cartItems)
            {
                _context.Carts.Remove(item);
            }
            _context.SaveChanges();
            return RedirectToAction("Details", "Orders", new { @id = order.Id });
        }

        // Helper method > not designed to be used outside of this class
        private string GetCustomerId()
        {
            // Check the session object for a CustomerId value
            // Session will be persisted as long as the user remains on the page
            // Once browser is closed Session might be lost
            if (String.IsNullOrEmpty(HttpContext.Session.GetString("CustomerId")))
            {
                string customerId = "";
                // check if the user is authenticated and use email address as id
                if (User.Identity.IsAuthenticated)
                {
                    customerId = User.Identity.Name; // email address
                }
                else
                {

ASP.NET-FinalExam-Starter-master/ASP.NET-FinalExam-Starter-master/DotNetDrinks/Views/Store/Browse.cshtml
@* Verify you are using the right model
    List implements IEnumerable interface
*@
@model IEnumerable<DotNetDrinks.Models.Product>

@{
    ViewData["Title"] = "Browse";
}

@if (ViewBag.category != null)
{
    <h1>@ViewBag.category</h1>
}
else
{
    <h1>Browse</h1>
}

@* To keep my design consistent *@
<section class="row card-group">
    @foreach (var product in Model)
    {
        <div class="col-sm-6 mb-3">
            <div class="card mb-6 text-center h-100">
                <div class="card-body">
                    <a asp-controller="Products"
                       asp-action="Details"
                       asp-route-id="@product.Id">@product.Name</a>
                    <h6>@product.Price.ToString("C")</h6>
                    <p>@product.Brand</p>
                    @if (String.IsNullOrEmpty(product.Image))
                    {
                        <img src="~/img/products/drinks-placeholder.png"
                             alt="Placeholder Image for @product.Name"
                             class="img-thumbnail" />
                    }
                    else
                    {
                        <img src="~/img/products/@product.Image"
                             alt="Logo for @product.Name"
                             class="img-thumbnail" />
                    }
                    <form method="post" action="/Store/AddToCart">
                        <input type="hidden" id="ProductId" name="ProductId" value="@product.Id" />
                        <div class="form-group">
                            <label class="form-control" for="Quantity">Quantity: </label>
                            <input name="Quantity" id="Quantity" required
                                   type="number" min="1" max="999" />
                        </div>
                        <button class="btn btn-primary">Add to Cart</button>
                    </form>
                </div>
            </div>
        </div>
    }
</section>

ASP.NET-FinalExam-Starter-master/ASP.NET-FinalExam-Starter-master/DotNetDrinks/Views/Store/Cart.cshtml
@model IEnumerable<DotNetDrinks.Models.Cart>

@{
    ViewData["Title"] = "Cart";
}

<h1>My Shopping Cart</h1>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Product)
            </th>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Products"
                       asp-action="Details"
                       asp-route-id="@item.ProductId">
                        @item.Product.Name
                    </a>
                </td>
                <td>
                    @* ADD IMG HERE *@
                </td>
                @* As a general rule, numbers are right-aligned when shown in a table *@
                <td class="text-right">
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td class="text-right">
                    @* use generic C format provider to format decimal to currency *@
                    @item.Price.ToString("C")
                </td>
                <td>
                    @* asp-controller by default is the same as the folder where view is *@
                    <a asp-action="RemoveFromCart" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
        <tr>
            <td colspan="4" class="text-right">@ViewBag.TotalAmount</td>
            <td>
                <a class="btn btn-primary" asp-action="Index">Continue Shopping</a>
                <a class="btn btn-success" asp-action="Checkout">Checkout</a>
            </td>
        </tr>
    </tbody>
</table>

ASP.NET-FinalExam-Starter-master/ASP.NET-FinalExam-Starter-master/DotNetDrinks/Views/Store/Checkout.cshtml
@model DotNetDrinks.Models.Order

@{
    ViewData["Title"] = "Checkout";
}

<h1>Checkout</h1>
<h4>Order</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Checkout">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" required />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" required />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <textarea asp-for="Address" class="form-control" required></textarea>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" required />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Province" class="control-label"></label>
                <input asp-for="Province" class="form-control" required />
                <span asp-validation-for="Province" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" required />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Payment >>" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Cart">Back to Cart</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASP.NET-FinalExam-Starter-master/ASP.NET-FinalExam-Starter-master/DotNetDrinks/Views/Store/Index.cshtml
@model IEnumerable<DotNetDrinks.Models.Category>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<section class="row card-group">
    @foreach (var item in Model)
    {
        <div class="col-sm-6 mb-3">
            <div class="card mb-6 text-center h-100">
                <div class="card-body">
                    <a asp-controller="Store" asp-action="Browse" asp-route-id="@item.Id">@item.Name</a>
                </div>
            </div>
        </div>
    }
</section>

ASP.NET-FinalExam-Starter-master/ASP.NET-FinalExam-Starter-master/DotNetDrinks/Views/Store/Payment.cshtml
<!-- Reference the API at the top of your page -->
<script src="https://js.stripe.com/v3/"></script>

<h1>Confirm Payment Amount</h1>

@* Add Stripe script tag *@
<!--<script src="https://checkout.stripe.com/checkout.js"
        class="stripe-button"
        data-key="@ViewBag.PublishableKey"
        data-amount="@ViewBag.Total"
        data-name="DotNetDrinks Store"
        data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
        data-locale="auto"
        data-currency="cad"></script>-->

@* Add a new button and javascript code to handle this redirect to Stripe *@
<section>
    <h4>Order Total: @((ViewBag.Total/100).ToString("C"))</h4>
    <button id="checkout-button" class="btn btn-primary">Process Payment</button>
</section>

<!-- This code will handle the call to Stripe -->
<script type="text/javascript">
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe("@ViewBag.PublishableKey");

    var checkoutButton = document.getElementById("checkout-button");

    checkoutButton.addEventListener("click", function () {
        // this is us > POST /Store/Payment
        fetch("/Store/Payment", {
        method: "POST"
        })
        .then(function (response) {
          return response.json();
        })
          .then(function (session) {
            // This is them
          return stripe.redirectToCheckout({ sessionId: session.id });
        })
        .then(function (result) {
          // If redirectToCheckout fails due to a browser or network
          // error, you should display the localized error message to your
          // customer using error.message.
          if (result.error) {
            alert(result.error.message);
          }
        })
        .catch(function (error) {
          console.log(error);
        });
    });
</script>